### ISSUE TITLE
Does the smoothed linear programming solver accept inequalities?

### ISSUE THREAD

**Issue by huevosabio** [databricks/spark-tfocs#27]
As the title say, if I want to add inequalities to the problem formulation in a linear program, would TFOCS allow it?

**Comment by staple** [comment]
Hi Ramon, the existing solver only accepts problems in standard form. So inequalities would need to removed, for example by using slack variables. There is an example of conversion to standard form (will a small dataset) here: 

https://github.com/databricks/spark-tfocs/blob/master/src/main/scala/org/apache/spark/mllib/optimization/tfocs/examples/TestMPSLinearProgram.scala

**Comment by huevosabio** [comment]
Thanks!
